In [15]:
%pip install numpy pandas matplotlib

Requirement already satisfied: numpy in /opt/miniconda3/envs/hft/lib/python3.14/site-packages (2.4.6)
Requirement already satisfied: pandas in /opt/miniconda3/envs/hft/lib/python3.14/site-packages (3.0.3)
Requirement already satisfied: matplotlib in /opt/miniconda3/envs/hft/lib/python3.14/site-packages (3.10.9)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/miniconda3/envs/hft/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /opt/miniconda3/envs/hft/lib/python3.14/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/miniconda3/envs/hft/lib/python3.14/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/miniconda3/envs/hft/lib/python3.14/site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/miniconda3/envs/hft/lib/python3.14/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /opt/miniconda3/envs/hft/lib/python3.14/site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in /opt/miniconda3/envs/hft/lib/python3.14/site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in /opt/miniconda3/envs/hft/lib/python3.14/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /opt/miniconda3/envs/hft/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [16]:
import numpy as np
import pandas as pd

In [17]:
df = pd.read_csv("./BTCUSDT-bookTicker-2024-03-29.csv")
df.head()

,update_id,best_bid_price,best_bid_qty,best_ask_price,best_ask_qty,transaction_time,event_time
0,4300610507170,70838.7,4.432,70838.8,2.089,1711670400005,1711670400012
1,4300610507402,70838.7,4.442,70838.8,2.089,1711670400008,1711670400014
2,4300610507423,70838.7,6.454,70838.8,2.089,1711670400008,1711670400014
3,4300610507585,70838.7,6.464,70838.8,2.089,1711670400009,1711670400016
4,4300610507791,70838.7,7.488,70838.8,2.089,1711670400011,1711670400017

In [18]:
# Find Covariance of first 100 entries 

df["spot_price"] = (df.best_ask_price + df.best_bid_price)/2

df.head(10000)

,update_id,best_bid_price,best_bid_qty,best_ask_price,best_ask_qty,transaction_time,event_time,spot_price
0,4300610507170,70838.7,4.432,70838.8,2.089,1711670400005,1711670400012,70838.75
1,4300610507402,70838.7,4.442,70838.8,2.089,1711670400008,1711670400014,70838.75
2,4300610507423,70838.7,6.454,70838.8,2.089,1711670400008,1711670400014,70838.75
3,4300610507585,70838.7,6.464,70838.8,2.089,1711670400009,1711670400016,70838.75
4,4300610507791,70838.7,7.488,70838.8,2.089,1711670400011,1711670400017,70838.75
...,...,...,...,...,...,...,...,...
9995,4300621809226,70852.1,2.297,70852.2,1.626,1711670499579,1711670499586,70852.15
9996,4300621810361,70852.1,2.297,70852.2,1.752,1711670499591,1711670499597,70852.15
9997,4300621810365,70852.1,2.297,70852.2,1.955,1711670499591,1711670499597,70852.15
9998,4300621810398,70852.1,2.297,70852.2,2.103,1711670499591,1711670499597,70852.15
9999,4300621810617,70852.1,2.297,70852.2,2.108,1711670499594,1711670499599,70852.15

In [19]:
# i = 1001
# hund_values = df["spot_price"].values.tolist()[i - 1000 - 1: i]
# # len(hund_values)
# hund_values

In [20]:
# variance = np.var(hund_values)
# variance

In [21]:
# current_spot_price = df.iloc[i].spot_price
# inventory_q = 0
# risk_factor = 0.4
# t_remaining = 1 # For continuous markets
# kappa = 1.5
# reservation_price = current_spot_price - (inventory_q * risk_factor * variance * t_remaining)

In [22]:
# delta = (1/ 2) * risk_factor * variance * t_remaining + (1/risk_factor)* np.log(1 + (risk_factor/kappa))

In [23]:
# price_ask = reservation_price + delta
# price_bid = reservation_price - delta

In [24]:
# price_ask

In [25]:
# price_bid

In [26]:
inventory_q = 0
risk_factor = 0.1
# t_remaining = 1 # For continuous markets
kappa = 1.5

price_ask_list = []
price_bid_list = []

total_time = (df.iloc[-1].event_time - df.iloc[0].event_time)

spot_prices = df["spot_price"].values.tolist()

In [ ]:
for i in range(1001, 2000):
    current_spot_price = spot_prices[i]
    hund_values = spot_prices[i - 1000 - 1: i]

    normalized_window = (hund_values / current_spot_price) * 100

    current_spot_norm = 100.0
    
    variance = np.var(normalized_window)
    t_remaining = (total_time - df.iloc[i].event_time)/total_time
    reservation_price = current_spot_norm - (inventory_q * risk_factor * variance * t_remaining)
    delta = (1/ 2) * risk_factor * variance * t_remaining + (1/risk_factor)* np.log(1 + (risk_factor/kappa))
    
    price_ask_norm = reservation_price + delta
    price_bid_norm = reservation_price - delta
    
    price_ask = (price_ask_norm / 100.0) * current_spot_price
    price_bid = (price_bid_norm / 100.0) * current_spot_price
    
    price_ask_list.append(price_ask)
    price_bid_list.append(price_bid)

In [28]:
print(price_ask_list)
print(price_bid_list)

[np.float64(71115.85450577867), np.float64(71116.25221292161), np.float64(71116.65059072684), np.float64(71117.0496391946), np.float64(71117.44935832472), np.float64(71117.84974811733), np.float64(71118.25080857227), np.float64(71118.65253968972), np.float64(71119.05494146902), np.float64(71119.45801391134), np.float64(71119.86175701597), np.float64(71120.26617078311), np.float64(71120.67125521267), np.float64(71121.07701030467), np.float64(71121.48343605897), np.float64(71121.89053247582), np.float64(71122.29829955507), np.float64(71122.70673729674), np.float64(71123.11584570073), np.float64(71123.52562476708), np.float64(71123.93607449601), np.float64(71124.34719488729), np.float64(71124.75898594072), np.float64(71125.17144765683), np.float64(71125.58458003536), np.float64(71125.99838307624), np.float64(71126.41285677972), np.float64(71126.8280011456), np.float64(71127.24381617382), np.float64(71127.66030186448), np.float64(71128.07745821764), np.float64(71128.49528523322), np.float64(71128.91378291113), np.float64(71129.33295125139), np.float64(71129.75279025389), np.float64(71130.17329991916), np.float64(71130.59448024676), np.float64(71131.01633123636), np.float64(71131.43885288872), np.float64(71131.86204520351), np.float64(71132.2859081808), np.float64(71132.71044182027), np.float64(71133.13564612239), np.float64(71133.56152108696), np.float64(71133.98806671395), np.float64(71134.41528300276), np.float64(71134.84316995407), np.float64(71135.27172756485), np.float64(71135.70095584128), np.float64(71136.1308547805), np.float64(71136.56142438135), np.float64(71136.99266464537), np.float64(71137.4245755716), np.float64(71137.85715716048), np.float64(71138.29040941178), np.float64(71138.72433232544), np.float64(71139.1589259015), np.float64(71139.59419014007), np.float64(71140.030125041), np.float64(71140.46673060424), np.float64(71140.90400683008), np.float64(71141.3419537167), np.float64(71141.78057126717), np.float64(71142.2198594798), np.float64(71142.65981835531), np.float64(71143.10044789294), np.float64(71143.54174809293), np.float64(71143.98371895542), np.float64(71144.42636048015), np.float64(71144.8696726678), np.float64(71145.31365551788), np.float64(71145.75830903037), np.float64(71146.20363320521), np.float64(71146.64962804245), np.float64(71147.0962935422), np.float64(71147.19071462439), np.float64(71147.28818412207), np.float64(71147.7413168576), np.float64(71148.1951822066), np.float64(71148.64978016901), np.float64(71149.10511074495), np.float64(71149.56117393436), np.float64(71150.01796973715), np.float64(71150.4754981535), np.float64(71150.93375918332), np.float64(71151.39275282659), np.float64(71151.85247908333), np.float64(71152.31293795355), np.float64(71152.77412943722), np.float64(71153.23605353438), np.float64(71153.698710245), np.float64(71154.16209956909), np.float64(71154.62622150664), np.float64(71155.09107605765), np.float64(71155.55666322216), np.float64(71156.0229830001), np.float64(71156.49003539153), np.float64(71156.95782039643), np.float64(71157.42633801479), np.float64(71157.89558824661), np.float64(71158.36557109177), np.float64(71158.8362865505), np.float64(71159.3077346227), np.float64(71159.77991530838), np.float64(71160.25282860754), np.float64(71160.72647452018), np.float64(71161.20085304628), np.float64(71161.67596418585), np.float64(71162.15180793876), np.float64(71162.62838430527), np.float64(71163.10569328522), np.float64(71163.5837348786), np.float64(71164.06250908511), np.float64(71164.54201590442), np.float64(71165.02225533653), np.float64(71165.50322738358), np.float64(71165.98493204438), np.float64(71166.46736931849), np.float64(71166.95053920524), np.float64(71167.3833129962), np.float64(71167.81673174522), np.float64(71168.12227817994), np.float64(71168.42825384268), np.float64(71166.86982231081), np.float64(71166.93364245992), np.float64(71167.25052532577), np.float64(71167.56799513177), np.float64(71167.88605187781), np.float64(71168.20469556391), np.float64(71168.5281697457), np.float64(71168.85223899127), np.float64(71169.17690330051), np.float64(71169.50216267345), np.float64(71169.7299122777), np.float64(71169.95807060438), np.float64(71170.17601963566), np.float64(71170.39435737341), np.float64(71170.61308381762), np.float64(71170.83219896829), np.float64(71171.05170282534), np.float64(71171.27159538896), np.float64(71171.49187665901), np.float64(71171.71254663552), np.float64(71171.93360531851), np.float64(71172.15505270795), np.float64(71172.37688880386), np.float64(71172.59911360624), np.float64(71172.82172711506), np.float64(71173.04472933036), np.float64(71173.26812025212), np.float64(71173.49189988033), np.float64(71173.71606821504), np.float64(71173.95141127426), np.float64(71174.19081771746), np.float64(71174.43990721292), np.float64(71174.68942941795), np.float64(71174.93938433252), np.float64(71175.18977195659), np.float64(71175.4405922902), np.float64(71175.6918453333), np.float64(71175.92325855892), np.float64(71176.15506710841), np.float64(71176.1856946199), np.float64(71176.36482686705), np.float64(71176.59307854199), np.float64(71176.67055139584), np.float64(71176.89992686336), np.float64(71177.13151322302), np.float64(71177.36351509108), np.float64(71177.59593246765), np.float64(71177.82876535268), np.float64(71178.06201374614), np.float64(71178.29567764806), np.float64(71178.52975705842), np.float64(71178.76425197723), np.float64(71178.9991624045), np.float64(71179.23448834025), np.float64(71179.47022978442), np.float64(71179.70638673705), np.float64(71179.94295919812), np.float64(71180.17994716758), np.float64(71180.41735064557), np.float64(71180.655169632), np.float64(71180.89340412687), np.float64(71180.27541636518), np.float64(71180.51565780268), np.float64(71180.75637466999), np.float64(71180.99756696717), np.float64(71180.38260846972), np.float64(71180.62403445963), np.float64(71180.86599983621), np.float64(71181.10850459951), np.float64(71181.35154874949), np.float64(71181.59513228614), np.float64(71181.8392552095), np.float64(71182.08391751956), np.float64(71182.32911921629), np.float64(71182.57486029972), np.float64(71182.82114076983), np.float64(71183.06796062663), np.float64(71183.31531987012), np.float64(71183.56321850025), np.float64(71183.81165651712), np.float64(71184.06063392069), np.float64(71184.31015071094), np.float64(71184.56020688788), np.float64(71184.81080245151), np.float64(71185.06193740184), np.float64(71185.31361173886), np.float64(71185.56582546256), np.float64(71185.81857857296), np.float64(71186.07187107002), np.float64(71186.3257029538), np.float64(71186.58007422426), np.float64(71186.83498488137), np.float64(71187.0904349252), np.float64(71187.34642435572), np.float64(71187.60295317296), np.float64(71187.86002137687), np.float64(71188.11762896746), np.float64(71188.37577594476), np.float64(71188.63446230872), np.float64(71188.89368805941), np.float64(71189.15345319676), np.float64(71189.41375772082), np.float64(71189.67460163156), np.float64(71189.93598492898), np.float64(71190.19790761285), np.float64(71190.46036968341), np.float64(71186.08818282485), np.float64(71186.3201663444), np.float64(71186.50272323212), np.float64(71186.73595537427), np.float64(71186.97014821465), np.float64(71187.15492009185), np.float64(71187.39037269002), np.float64(71187.62679117298), np.float64(71187.86417554076), np.float64(71188.10252579334), np.float64(71188.34184193068), np.float64(71188.5821239529), np.float64(71188.82337185988), np.float64(71189.06558565171), np.float64(71189.30876532831), np.float64(71189.55291088978), np.float64(71189.79802233604), np.float64(71190.04409966712), np.float64(71190.29114288301), np.float64(71190.53915198373), np.float64(71190.7881269692), np.float64(71191.03806783954), np.float64(71191.28897459467), np.float64(71191.54084723462), np.float64(71191.79368575911), np.float64(71192.04749016865), np.float64(71192.30226046267), np.float64(71192.55799664187), np.float64(71192.8146987059), np.float64(71193.07236665468), np.float64(71193.33100048824), np.float64(71193.59060020668), np.float64(71193.8511658099), np.float64(71194.11269729749), np.float64(71194.37519467037), np.float64(71194.63865792807), np.float64(71194.90308707059), np.float64(71195.16848209791), np.float64(71195.43484301), np.float64(71195.70216980694), np.float64(71195.97046248864), np.float64(71196.23972105522), np.float64(71196.50994550658), np.float64(71196.7811358428), np.float64(71197.05329206359), np.float64(71197.32641416941), np.float64(71197.60050216004), np.float64(71197.87555603545), np.float64(71198.15157579558), np.float64(71198.42856144026), np.float64(71198.70651296998), np.float64(71198.98543038467), np.float64(71199.12046385091), np.float64(71199.2560843136), np.float64(71199.39229177272), np.float64(71199.5290862282), np.float64(71199.66646768012), np.float64(71199.80443612844), np.float64(71199.9429915732), np.float64(71200.08213401442), np.float64(71200.22186345197), np.float64(71200.36217988598), np.float64(71200.50308331585), np.float64(71200.64457374276), np.float64(71200.78665116605), np.float64(71200.92931558455), np.float64(71201.07256700071), np.float64(71201.21640541322), np.float64(71201.36083082222), np.float64(71201.50584322748), np.float64(71201.65144262857), np.float64(71201.7976290263), np.float64(71201.94440242101), np.float64(71202.09176281204), np.float64(71202.23971019957), np.float64(71202.38824458352), np.float64(71202.5373659639), np.float64(71202.68707434066), np.float64(71202.83736971387), np.float64(71202.98825208347), np.float64(71203.13972144945), np.float64(71203.29177781194), np.float64(71203.44442117083), np.float64(71203.59765152616), np.float64(71203.75146887789), np.float64(71203.90587322605), np.float64(71208.6445092225), np.float64(71208.81445532017), np.float64(71208.98467780488), np.float64(71209.20554603451), np.float64(71209.376153956), np.float64(71209.54703549355), np.float64(71209.71819064717), np.float64(71209.8896194169), np.float64(71210.06132180273), np.float64(71210.23329780465), np.float64(71210.40554742263), np.float64(71210.57807065672), np.float64(71210.7508675069), np.float64(71210.92393797314), np.float64(71211.09728205546), np.float64(71211.2708997539), np.float64(71211.44479106841), np.float64(71211.61895599894), np.float64(71211.79339454565), np.float64(71211.96810670842), np.float64(71212.14309248721), np.float64(71212.31835188212), np.float64(71212.49388489312), np.float64(71212.66969152026), np.float64(71212.84577176342), np.float64(71213.02212562272), np.float64(71213.19875309808), np.float64(71213.37565418948), np.float64(71213.55282889704), np.float64(71213.73027722037), np.float64(71213.90799915996), np.float64(71214.08599471535), np.float64(71214.26426388725), np.float64(71214.44280667524), np.float64(71214.62162307934), np.float64(71214.80071309951), np.float64(71214.98007673577), np.float64(71215.15971398698), np.float64(71215.33962485468), np.float64(71215.51980933921), np.float64(71215.70026743968), np.float64(71215.88099915592), np.float64(71216.0620044883), np.float64(71216.24328343703), np.float64(71216.42483600197), np.float64(71216.60666218246), np.float64(71216.7887619796), np.float64(71216.97113539277), np.float64(71217.15378242209), np.float64(71217.33670306721), np.float64(71217.51989732863), np.float64(71217.7033652062), np.float64(71217.88710669958), np.float64(71218.07112180929), np.float64(71218.25541053453), np.float64(71218.43997287638), np.float64(71218.62480883213), np.float64(71218.78629671979), np.float64(71218.94649822667), np.float64(71219.1069309156), np.float64(71219.26607912888), np.float64(71219.42545598923), np.float64(71219.5835503085), np.float64(71219.74036530337), np.float64(71219.89740391944), np.float64(71220.05167123614), np.float64(71220.20615720644), np.float64(71220.35937238729), np.float64(71220.51280375956), np.float64(71220.663488502), np.float64(71220.81438454927), np.float64(71220.96255219681), np.float64(71221.11092631967), np.float64(71221.25804515439), np.float64(71221.4039121068), np.float64(71221.54998076078), np.float64(71221.69625111621), np.float64(71221.84272317048), np.float64(71221.98939692683), np.float64(71222.13627238666), np.float64(71222.28334954788), np.float64(71222.43062841077), np.float64(71222.57810897507), np.float64(71222.72579124094), np.float64(71222.87367520815), np.float64(71223.02176087695), np.float64(71223.170048247), np.float64(71223.31853731879), np.float64(71223.46722809074), np.float64(71223.6161205635), np.float64(71223.76521473916), np.float64(71223.91451061679), np.float64(71224.06400819587), np.float64(71224.21370747653), np.float64(71224.3636084567), np.float64(71224.51371113985), np.float64(71224.6640155237), np.float64(71224.81452161034), np.float64(71224.96522939768), np.float64(71225.11613888729), np.float64(71225.26725007826), np.float64(71225.41856297072), np.float64(71225.57007756452), np.float64(71225.72179385992), np.float64(71225.87371185693), np.float64(71226.02583155541), np.float64(71226.178152954), np.float64(71226.3306760552), np.float64(71226.4834008581), np.float64(71226.6363273625), np.float64(71226.78945556823), np.float64(71226.94278547364), np.float64(71227.09631708245), np.float64(71227.25005039273), np.float64(71227.4039854045), np.float64(71227.5581221161), np.float64(71227.71246052902), np.float64(71227.867000645), np.float64(71228.0217424628), np.float64(71228.1766859815), np.float64(71228.33183120216), np.float64(71228.48717812405), np.float64(71228.64272674665), np.float64(71228.79847706783), np.float64(71228.9544290921), np.float64(71229.11058281969), np.float64(71229.26693824652), np.float64(71229.42349537744), np.float64(71229.5802542078), np.float64(71229.73721474191), np.float64(71229.89437697745), np.float64(71230.0517409144), np.float64(71230.20930655289), np.float64(71230.36707389289), np.float64(71230.5250429343), np.float64(71230.68321367698), np.float64(71230.84158612139), np.float64(71231.00016026315), np.float64(71231.15893610999), np.float64(71231.31791365739), np.float64(71231.47709290781), np.float64(71231.63647385972), np.float64(71231.79605651314), np.float64(71231.95584086803), np.float64(71232.11582692443), np.float64(71232.27601468221), np.float64(71232.43640414049), np.float64(71232.59699530133), np.float64(71232.75778816294), np.float64(71232.91878272673), np.float64(71233.07997899198), np.float64(71233.24137695838), np.float64(71233.40297662564), np.float64(71233.56477799386), np.float64(71233.726781065), np.float64(71233.88898583685), np.float64(71234.05139230988), np.float64(71234.21400048536), np.float64(71234.3768103625), np.float64(71234.53982194), np.float64(71234.70303522014), np.float64(71239.19665672329), np.float64(71239.30270537027), np.float64(71239.40880326014), np.float64(71239.38915645343), np.float64(71239.3695130245), np.float64(71239.34987297333), np.float64(71239.33023629994), np.float64(71239.29637068123), np.float64(71239.26251679401), np.float64(71239.22867463822), np.float64(71239.19349464079), np.float64(71239.15700654557), np.float64(71239.11924018028), np.float64(71239.08278097755), np.float64(71239.04633590706), np.float64(71239.00861447869), np.float64(71238.95954854721), np.float64(71238.90383663436), np.float64(71238.84740136204), np.float64(71238.79101533261), np.float64(71239.08713948641), np.float64(71239.37640010825), np.float64(71239.30600673829), np.float64(71239.23568039271), np.float64(71239.1654210715), np.float64(71239.09522877465), np.float64(71239.02510350216), np.float64(71238.95504525401), np.float64(71238.88505403028), np.float64(71238.81512983087), np.float64(71238.74527265581), np.float64(71238.67548250516), np.float64(71238.60575937892), np.float64(71238.536103277), np.float64(71238.46651419949), np.float64(71238.3969921463), np.float64(71238.32753711753), np.float64(71238.25743230688), np.float64(71238.18739728421), np.float64(71238.11814606423), np.float64(71238.0489618686), np.float64(71237.97984469734), np.float64(71237.91079455042), np.float64(71237.8418114279), np.float64(71237.77289532966), np.float64(71237.70404625585), np.float64(71237.6352642064), np.float64(71237.56654918134), np.float64(71237.49719947625), np.float64(71237.42791955941), np.float64(71237.35803848901), np.float64(71237.28823002585), np.float64(71237.21849417003), np.float64(71237.1488309211), np.float64(71237.07924028028), np.float64(71237.0097222469), np.float64(71236.94027682088), np.float64(71236.87090400231), np.float64(71236.80160379117), np.float64(71236.73237618542), np.float64(71236.66322118908), np.float64(71236.5889470982), np.float64(71236.51477858852), np.float64(71236.44071566098), np.float64(71236.36675831678), np.float64(71236.29242692316), np.float64(71236.2182063249), np.float64(71236.14409652205), np.float64(71236.07009751456), np.float64(71235.99620930248), np.float64(71235.92243188577), np.float64(71235.84876526445), np.float64(71235.77520943852), np.float64(71235.70176440798), np.float64(71235.62843017282), np.float64(71235.55520673301), np.float64(71235.48209408861), np.float64(71235.40909223961), np.float64(71235.33620118599), np.float64(71235.26342092776), np.float64(71235.19075146494), np.float64(71235.11819279732), np.float64(71235.04574492523), np.float64(71234.97340784478), np.float64(71234.90118156343), np.float64(71234.82906607683), np.float64(71234.75706138521), np.float64(71234.68516748957), np.float64(71234.61338438978), np.float64(71234.54171208368), np.float64(71234.47015057284), np.float64(71234.39869985629), np.float64(71234.32645310924), np.float64(71234.25413269785), np.float64(71234.1819446812), np.float64(71234.10989937399), np.float64(71234.0379967749), np.float64(71233.96626284771), np.float64(71233.89476963294), np.float64(71233.8268915804), np.float64(71233.75922725462), np.float64(71233.69177665481), np.float64(71233.62477093222), np.float64(71233.55798138521), np.float64(71233.49215079477), np.float64(71233.42654381196), np.float64(71233.36116043673), np.float64(71233.29626599564), np.float64(71233.23303547398), np.float64(71233.1703536313), np.float64(71233.10823135042), np.float64(71233.04701294114), np.float64(71232.98638554651), np.float64(71232.9267171642), np.float64(71232.86767141464), np.float64(71232.80925932745), np.float64(71232.7514919486), np.float64(71232.69477774328), np.float64(71232.63999941113), np.float64(71232.5855030296), np.float64(71232.529612347), np.float64(71232.47888653901), np.float64(71232.42846266182), np.float64(71232.37834071598), np.float64(71232.32852070019), np.float64(71232.2790026148), np.float64(71232.22978646112), np.float64(71232.18087223622), np.float64(71232.13225994381), np.float64(71232.08394958156), np.float64(71232.03594114856), np.float64(71231.98823464818), np.float64(71231.94083007853), np.float64(71231.89372743937), np.float64(71231.8469267259), np.float64(71231.80042794823), np.float64(71231.7542311014), np.float64(71231.70833618082), np.float64(71231.66274319234), np.float64(71231.6174521374), np.float64(71231.57246301332), np.float64(71231.52777581994), np.float64(71231.4833905572), np.float64(71231.43930722502), np.float64(71231.39552582365), np.float64(71231.35204635262), np.float64(71231.30886881155), np.float64(71231.26599320097), np.float64(71231.22341952228), np.float64(71231.18114777427), np.float64(71231.13917795589), np.float64(71231.09751006906), np.float64(71231.05614411314), np.float64(71231.01508008743), np.float64(71231.03069500603), np.float64(71231.04894446248), np.float64(71231.06986820891), np.float64(71231.09242696145), np.float64(71231.11555256696), np.float64(71231.13924502555), np.float64(71231.16242624517), np.float64(71231.18617034648), np.float64(71231.21047733004), np.float64(71231.23752226334), np.float64(71231.299877643), np.float64(71231.36292549381), np.float64(71231.41274807631), np.float64(71231.46321561212), np.float64(71231.51432810024), np.float64(71231.56608554044), np.float64(71231.61848793372), np.float64(71231.67153527966), np.float64(71231.725227577